### PR TITLE
added support for the http patch method

### PR DESCRIPTION
**Pull request by Dinosys**

### CODE REVIEW

**Comment by Dinosys** [comment]
Not quite sure what went wrong with the greeting step, but hope the rest is ok

**Comment by grug** [comment]
Haha how odd! Thanks for raising this PR! I'll do a release with these changes today!

**Review by grug — APPROVED** [review]

**Comment by grug** [comment]
Once again, thank you so much for your contribution. Out of curiosity, may I ask how you heard about data-mocks @Dinosys

**Comment by mpoelstra** [comment]
> Once again, thank you so much for your contribution. Out of curiosity, may I ask how you heard about data-mocks @Dinosys

Well, we saw your presentation @ Angular Connect in London and soon after we started using your tool and told people like @Dinosys about it :) Now we're using it a lot in several apps. Nice work!

**Comment by Dinosys** [comment]
Quite right, loving this tool for local development.
We use it in angular

**Comment by grug** [comment]
That's awesome 👍 

I've just published version 4.0.2!

**Comment by krzysiekpiasecki** [comment]
This is the API extension. You should bump minor version and reset the patch, instead of bumping patch version. BTW This is great tool, which I use in my daily routine (also saw it for the first time on YT #AngularConnect).

**Pull request merged**
